name: CI/CD Render

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clear Docker auth
        run: |
          unset DOCKER_AUTH_CONFIG
          rm -f ~/.docker/config.json || true
          mkdir -p ~/.docker

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        env:
          IMAGE: ghcr.io/${{ github.repository_owner }}/flask-render-iac:${{ github.sha }}
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        env:
          IMAGE: ${{ env.IMAGE }}
        run: |
          terraform apply -auto-approve \
            -var="render_api_key=${{ secrets.RENDER_API_KEY }}" \
            -var="render_owner_id=${{ secrets.RENDER_OWNER_ID }}" \
            -var="image_url=${IMAGE}"
        working-directory: terraform
